### ISSUE TITLE
개선사항

### ISSUE THREAD

**Issue by dbckdgjs369** [dbckdgjs369/Youtube_Playlist_Generator#24]
## bugs
- [x] 로딩에서 마치고 돌아왔을 때 창이 리렌더링 되며 textarea 값이 사라짐. (투명도를 주면 될 수도?)
- [x] textarea 값이 바뀔경우 전체 선택의 개수가 안바뀜
- [ ] 가끔씩 안들어가는 노래가 있음
## todos
- [ ] 추가 완료하고 몇곡을 ~에 넣었다고 alert 띄우기
- [ ] 원래 있는 플레이 리스트에도 넣을 수 있게 해주면 좋을 듯
- [ ] refresh token 추가
